---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-events

--- 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  finalizers: 
    - resources-finalizer.argocd.argoproj.io
  name: argo-events
  namespace: argocd
spec: 
  destination: 
    namespace: argo-events
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    chart: argo-events
    repoURL: "https://argoproj.github.io/argo-helm"
    targetRevision: "2.0.6"
    helm:
      values: |
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
          - argo-workflows.michaelmcnairy.com
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true

