--- 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: gitops-core
  finalizers: 
  - resources-finalizer.argocd.argoproj.io
  name: nginx-ingress-controller
  namespace: argocd
spec:
  project: default
  source:
    path: helm
    repoURL: 'git@github.com:McNairy/gitops-core.git'
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd

