apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm
    repoURL: https://github.com/McNairy/gitops-monitoring-grafana.git
    targetRevision: HEAD
  helm:
    values: |
      image:
        tag: latest
      ingress:
        host: grafana.mcnairy-manor.home
    version: v3
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
