--- 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  finalizers: 
    - resources-finalizer.argocd.argoproj.io
  name: loki
  namespace: argocd
spec: 
  destination: 
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    chart: grafana-loki
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: "2.4.4"
    helm:
      values: |
        service:
          type: LoadBalancer
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true

