--- 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  finalizers: 
  - resources-finalizer.argocd.argoproj.io
  name: nginx-ingress-controller
  namespace: argocd
spec: 
  destination:
    name: '' 
    namespace: nginx-ingress
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: nginx-ingress-controller
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 9.3.18
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-http-ingress
  namespace: nginx-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.1.0/24
spec:
  ingressClassName: nginx
  rules:
  - host: argocd.mcnairy-manor.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: http
