project: default
destination:
  namespace: nginx-ingress
  server: 'https://kubernetes.default.svc'
source:
  repoUrl: 'https://charts.bitnami.com/bitnami'
  targetRevision: 9.3.18
  chart: nginx-ingress-controller
syncPolicy:
  automated:
    prune: true
    selfHeal: true
