--- 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  finalizers: 
    - resources-finalizers.argocd.proj.io
  name: nginx-ingress
  namespace: argocd
spec: 
  destination: 
    namespace: nginx-ingress
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    chart: nginx-ingress-controller
    path: nginx-ingress-controller
    repoUrl: "https://charts.bitnami.com/bitnami"
    targetRevision: "9.3.18"
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true
