apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
  finalizers:
    - resources-finalizers.argocd.proj.io
spec:
  project: default
  destination:
    namespace: nginx-ingress
    server: 'https://kubernetes.default.svc'
  source:
    path: nginx-ingress-controller
    repoUrl: 'https://charts.bitnami.com/bitnami'
    targetRevision: 9.3.18
    chart: nginx-ingress-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
