--- 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  finalizers: 
    - resources-finalizer.argocd.argoproj.io
  name: nginx-ingress-controller
  namespace: argocd
spec: 
  destination:
    name: '' 
    namespace: nginx-ingress
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: nginx-ingress-controller
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 9.3.18
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true
