--- 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  finalizers: 
  - resources-finalizer.argocd.argoproj.io
  name: opentelemetry-collector
  namespace: argocd
spec: 
  destination:
    name: '' 
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: opentelemetry-collector
    path: ''
    repoURL: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
    targetRevision: "0.35.0"
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true

