--- 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  finalizers: 
    - resources-finalizer.argocd.argoproj.io
  name: prometheus
  namespace: argocd
spec: 
  destination: 
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    chart: prometheus
    helm: 
      values: |
        server:
          global:
            scrape_interval: 5s
            evaluation_interval: 5s
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              kubernetes.io/tls-acme: 'true'
              cert-manager.io/cluster-issuer: letsencrypt-staging
            hosts:
              - prometheus.mcnairy-manor.home
            extraPaths:
            - paths: /*
              backend:
                serviceName: ssl-redirect
                servicePort: use-annotation
            tls:
              - secretName: prometheus-server-tls
                hosts:
                  - prometheus.mcnairy-manor.home
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: "15.15.0"
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true

