apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress-resource
  namesspace: nginx-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
  - hosts:
    - prometheus.mcnairy-manor.home
    secretName: letsencrypt-staging
  rules:
  - host: prometheus.mcnairy-manor.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
