---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  project: default
  source:
    chart: prometheus
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: "15.15.0"
    helm:
      values: |
        server:
          global:
            evaluation_interval: 5s
            scrape_interval: 5s
            scrape_timeout: 5s
        # nodeExporter:
        #   enabled: true
        # serverFiles:
        #   prometheus.yaml:
        #     scrape_configs:
        #       - job_name: node-exporter
        #         static_configs:
        #           - targets:
        #             - 192.168.1.41:9090
        #             - 192.168.1.7:9090
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
