--- 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  finalizers: 
    - resources-finalizer.argocd.argoproj.io
  name: prometheus
  namespace: argocd
spec: 
  destination: 
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    chart: prometheus
    helm: 
      values: |
        server:
          global:
            scrape_interval: 5s
            evaluation_interval: 5s
          ingress:
            enabled: true
            hosts:
              - prometheus.mcnairy-manor.home
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: "15.15.0"
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true

