apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress-resource
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
  - hosts:
    - prometheus.michaelmcnairy.com
    secretName: prometheus-server-tls
  rules:
  - host: prometheus.michaelmcnairy.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-server
            port:
              number: 80
